
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuxikzjnptutswjrfmog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1eGlrempucHR1dHN3anJmbW9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjU3MDUsImV4cCI6MjA2MjgwMTcwNX0.TMydOAVAot8O1-4Ae4jN73p-Z49oR6eXwob6_ObnjHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function for running the test users edge function
export async function createTestUsers() {
  try {
    const { data, error } = await supabase.functions.invoke('create-test-users');
    
    if (error) {
      throw error;
    }
    
    return data;
  } catch (error) {
    console.error('Error creating test users:', error);
    throw error;
  }
}

// Helper function for creating test data
export async function createTestData() {
  try {
    // Wir verwenden hier die Edge-Function, die bereits vorhanden ist
    // Diese Funktion wird die Berechtigungsprobleme umgehen können
    const { data, error } = await supabase.functions.invoke('create-test-data');
    
    if (error) {
      throw error;
    }
    
    return data;
  } catch (error) {
    console.error('Error creating test data:', error);
    throw error;
  }
}
